# Generated by Django 2.2.5 on 2019-10-04 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_studentfees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentfees',
            old_name='Comment',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='studentfees',
            old_name='Student',
            new_name='student',
        ),
    ]
