# Generated by Django 2.2.5 on 2019-10-04 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20191004_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfees',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1220.22, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentfees',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
